@host http://localhost:9200

### Get all indexes help
GET /_cat/indices?help=true

### Get all indexes
GET /_cat/indices?h=index

### Get all streams
GET /_data_stream

### Get all index tempaltes
GET /_template

