openapi: 3.0.0
info:
  version: '2'
  title: MyLab.Search.Indexer API
servers:
  - url: https://api.example.com/v2
paths:
  '/indexes/{idx_id}':
  
    parameters: 
      - $ref: '#/components/parameters/IndexId'
  
    post:
      tags:
      - Indexing 
      summary: Index new entity without specified identifier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '200':
          description: The entity was indexed successful
        '400':
          description: The request is malformed
        '404':
          description: Index not found
  
  '/indexes/{idx_id}/{ent_id}':
          
    parameters:
      - $ref: '#/components/parameters/IndexId'
      - $ref: '#/components/parameters/EntityId'
      
    post:
      tags:
      - Indexing 
      summary: Index new entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '200':
          description: The entity was indexed successful
        '400':
          description: The request is malformed
        '404':
          description: Index not found
      
    put:
      tags:
      - Indexing 
      summary: Index new entity or reindex if already indexed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '200':
          description: The entity was indexed successful
        '400':
          description: The request is malformed
        '404':
          description: Index or an entity not found
          
    patch:
      tags:
      - Indexing 
      summary: Merge specified partial data with indexed entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '200':
          description: The data was merged successful
        '400':
          description: The request is malformed
        '404':
          description: Index or an entity not found
          
    delete:
      tags:
      - Indexing 
      summary: Remove specified entity from index
      responses:
        '200':
          description: The entity was removed successful or does not exist
        '400':
          description: The request is malformed
        '404':
          description: Index not found
          
  '/indexes/{idx_id}/{ent_id}/kicker':
  
    parameters:
      - $ref: '#/components/parameters/IndexId'
      - $ref: '#/components/parameters/EntityId'
  
    post:
      tags:
      - Indexing 
      summary: Kick to index an entity with specified id from data source
      requestBody:
        content:
          application/json:
            schema:
              type: string
              example: 12-34443
      responses:
        '200':
          description: The entity was indexed successful
        '400':
          description: The request is malformed
        '404':
          description: Index or an entity not found
  
components:
  parameters:
    
    EntityId:
      name: ent_id
      in: path
      required: true
      description: Indexed entity identifier
      schema:
        type:
          string
      example: 123
    
    IndexId:
      name: idx_id
      in: path
      required: true
      description: Index identifier
      schema:
        type:
          string
      example: orders
      
  schemas:
    
    Entity:
      type: object
      additionalProperties: true
      example:
        id: 2
        value: "foo"